### ISSUE TITLE
Upgrade google-cloud-secret-manager dependency

### ISSUE THREAD

**Issue by spbnick** [kernelci/kcidb#111]
The latest release of the `google-cloud-secret-manager` package breaks the existing KCIDB code, and was pinned to versions <2.0.0dev.

Fix the incompatibilities and unpin the package. Or perhaps re-pin to <3.0.0dev.

**Comment by spbnick** [comment]
Provided you have created a Google Cloud project named "foo", you created a secret in the password manager named "bar", and have the project access credentials in a `~/.google-cloud-credentials.json` file, you can reproduce the issue like this (from the repo's top directory):

```bash
virtualenv --python=python3.9 kcidb-bug-env
. ./kcidb-bug-env/bin/activate
git apply <<END
diff --git a/setup.py b/setup.py
index c728016..57019c7 100644
--- a/setup.py
+++ b/setup.py
@@ -43,7 +43,7 @@ setuptools.setup(
         "google-cloud-bigquery",
         "google-cloud-pubsub<2.0.0dev",
         "google-cloud-firestore",
-        "google-cloud-secret-manager<2.0.0dev",
+        "google-cloud-secret-manager",
         "jsonschema[format]",
         "requests",
         "pyyaml",
END
pip3 install -e '.[dev]'
python3 -c 'from kcidb.misc import get_secret; print(get_secret("kernelci-production", "foobar"))'
```

The problem will manifest something like this:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/nkondras/projects/github.com/kernelci/kcidb/kcidb/misc.py", line 302, in get_secret
    return client.access_secret_version(path).payload.data.decode()
  File "/home/nkondras/tmp/kcidb-bug-env/lib/python3.9/site-packages/google/cloud/secretmanager_v1/services/secret_manager_service/client.py", line 1123, in access_secret_version
    request = service.AccessSecretVersionRequest(request)
  File "/home/nkondras/tmp/kcidb-bug-env/lib/python3.9/site-packages/proto/message.py", line 494, in __init__
    raise TypeError(
TypeError: Invalid constructor input for AccessSecretVersionRequest: 'projects/kernelci-production/secrets/foobar/versions/latest'
```

A working solution should print the retrieved secret.

**Comment by spbnick** [comment]
Provided you have created a Google Cloud project (first thing you do when signing up, free trial available) named "foo", you created a secret in the [secret manager](https://console.cloud.google.com/security/secret-manager) named "bar", and have the project access credentials in a `~/.google-cloud-credentials.json` file, you can reproduce the issue like this (from the repo's top directory):

```bash
virtualenv --python=python3.9 kcidb-bug-env
. ./kcidb-bug-env/bin/activate
git apply <<END
diff --git a/setup.py b/setup.py
index c728016..57019c7 100644
--- a/setup.py                                                                                                                                                                                 
+++ b/setup.py
@@ -43,7 +43,7 @@ setuptools.setup(
         "google-cloud-bigquery",
         "google-cloud-pubsub<2.0.0dev",
         "google-cloud-firestore",
-        "google-cloud-secret-manager<2.0.0dev",
+        "google-cloud-secret-manager",
         "jsonschema[format]",
         "requests",
         "pyyaml",
END
pip3 install -e '.[dev]'
export GOOGLE_APPLICATION_CREDENTIALS=~/.google-cloud-credentials.json
python3 -c 'from kcidb.misc import get_secret; print(get_secret("foo", "bar"))'
```

The problem will manifest something like this:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/nkondras/projects/github.com/kernelci/kcidb/kcidb/misc.py", line 302, in get_secret
    return client.access_secret_version(path).payload.data.decode()
  File "/home/nkondras/tmp/kcidb-bug-env/lib/python3.9/site-packages/google/cloud/secretmanager_v1/services/secret_manager_service/client.py", line 1123, in access_secret_version
    request = service.AccessSecretVersionRequest(request)
  File "/home/nkondras/tmp/kcidb-bug-env/lib/python3.9/site-packages/proto/message.py", line 494, in __init__
    raise TypeError(
TypeError: Invalid constructor input for AccessSecretVersionRequest: 'projects/kernelci-production/secrets/foobar/versions/latest'
```

A working solution should print the retrieved secret.
